plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    - "semantic-release-helm3"
    - 
      chartPath: "./prima-api/"
      updateChartVersion: true
  - 
    - "@semantic-release/exec"
    - 
      prepareCmd: |
        # Update version and appVersion in Chart.yaml
        sed -i 's/^version: .*/version: ${nextRelease.version}/' ./prima-api/Chart.yaml
        sed -i 's/^appVersion: .*/appVersion: "${nextRelease.version}"/' ./prima-api/Chart.yaml
  - 
    - "@semantic-release/git"
    - 
      assets:
        - "CHANGELOG.md"               
        - "prima-api/Chart.yaml"
      message: "chore(release): update CHANGELOG and Chart.yaml to version ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"

tagFormat: "${version}"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - master
  - next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
