version: '3.9'
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    expose:
      - "9000"

  
  nginx:
    platform: linux/amd64
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "8000:8000"

