# Default values for prima-api.

replicaCount: 2
namespace: bruvio-poc


image:
  app:
    repository: bruvio/prima-sre-app
    tag: latest
    pullPolicy: IfNotPresent
  nginx:
    repository: bruvio/prima-sre-nginx
    tag: latest
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer  
  port: 80  
  targetPort: 8000 

containerPorts:
  app: 9000    # FastAPI app 
  nginx: 8000  # Nginx proxy 

ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: api.brunoviola.net
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
  nginxConfig: nginx.conf

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}


env:
  - name: AWS_REGION
    value: eu-west-2
  - name: DYNAMO_TABLE
    value: Users
  - name: S3_BUCKET
    value: my-api-avatars


awsSecret:
  name: aws-credentials
  accessKeyIdKey: AWS_ACCESS_KEY_ID
  secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
