apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prima-api.fullname" . }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    pid /tmp/nginx.pid;  

    events {
      worker_connections 1024;
    }

    http {
      access_log /dev/stdout;
      error_log /dev/stderr warn;  

      upstream fastapi {
        server 127.0.0.1:9000;
      }

      server {
        listen 8000;
        
        location / {
          proxy_pass http://fastapi;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
          proxy_pass http://fastapi/health;
        }
      }
    }
